Tease Server/Tease Server/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tease_Server.Models;

namespace Tease_Server.Controllers
{
    public class MainController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Tease?pageID=1
        public ActionResult Index(int pageID)
        {
            Page p = db.Pages.Find(pageID);
            ViewBag.pageID = pageID.ToString();
            ViewBag.pageName = p.Name;
            ViewBag.projectID = p.ProjectID;
            return View();
        }

    }
}

Tease Server/Tease Server/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tease_Server.Models;
using Ionic.Zip;

namespace Tease_Server.Controllers
{
    public class ProjectController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Project/

        [Authorize]
        public ActionResult Index()
        {
            try
            {
                UserProfile user = getUser();
                var projects = from p in db.Projects
                               where p.UserID == user.UserId
                               select p;
                return View(projects.ToList());
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Details/5
        [Authorize]
        public ActionResult Details(int id = 0)
        {
            try
            {
                UserProfile user = getUser();
                Project project = db.Projects.Find(id);
                if (project == null || project.UserID != user.UserId)
                {
                    return HttpNotFound();
                }
                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Project/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Project project)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (db.Projects.Where(x => x.Name == project.Name).Count() > 0)
                    {
                        ViewBag.DuplicateErrorMessage = "Ya existe un proyecto con ese nombre. Elige otro por favor.";
                        return View(project);
                    }
                    project.ModificationDate = DateTime.Now;
                    project.CreationDate = DateTime.Now;
                    project.UserID = getUser().UserId;
                    db.Projects.Add(project);
                    db.SaveChanges();
                    System.IO.Directory.CreateDirectory(Server.MapPath("~/PagesFiles/" + project.ProjectID + "/res/"));
                    return RedirectToAction("Index");
                }

                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            try
            {
                Project project = db.Projects.Find(id);
                if (project == null || project.User.UserName != User.Identity.Name)
                {
                    return HttpNotFound();
                }
                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // POST: /Project/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Project project)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Project p = db.Projects.Find(project.ProjectID);
                    if (p.UserID == getUser().UserId)
                    {
                        db.Projects.Attach(p);
                        p.Name = project.Name;
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            try
            {
                Project project = db.Projects.Find(id);
                UserProfile user = getUser();
                if (project == null || user.UserId != project.UserID)
                {
                    return HttpNotFound();
                }
                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // POST: /Project/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Project project = db.Projects.Find(id);
                if (project.UserID == getUser().UserId)
                {
                    db.Projects.Remove(project);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Zip/projectID

        [Authorize]
        public ActionResult Zip(int projectID)
        {
            string directoryPath = Server.MapPath("/PagesFiles/" + projectID + "/");
            using (ZipFile file = new ZipFile())
            {
                Project project = db.Projects.Find(projectID);
                var pages = from p in db.Pages
                             where p.ProjectID == projectID
                             select p;

                foreach (Page p in pages.ToList())
                {
                    if (System.IO.File.Exists(directoryPath + p.PageID + "/page.zip"))
                    {
                        System.IO.File.Delete(directoryPath + p.PageID + "/page.zip");
                    }
                    file.AddDirectory(directoryPath + p.PageID, project.Name + "/" + p.Name); 
                }
                file.AddDirectory(directoryPath + "res", project.Name + "/res");
                file.Save(directoryPath + "project.zip");
            }
            return base.File(directoryPath + "project.zip", "application/zip");
        }
        
        private UserProfile getUser()
        {
            var user = from s in db.UserProfiles
                       where String.Equals(s.UserName, User.Identity.Name)
                       select s;
            return user.ToList()[0];
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Tease Server/Tease Server/Views/Page/Create.cshtml
@model Tease_Server.Models.Page

@{
    ViewBag.Title = "Crear";
}

<h2>@ViewBag.ProjectName - Crear Página</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    @ViewBag.DuplicateErrorMessage
    <fieldset>
        <legend>Página</legend>

        @Html.Hidden("ProjectID", (string)ViewBag.projectID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <p>
            <input type="submit" value="Crear" />
        </p>
    </fieldset>
}

<div>
     Regresar a @Html.ActionLink((string)ViewBag.ProjectName, "Index", new { projectID = ViewBag.projectId})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tease Server/Tease Server/Views/Page/Delete.cshtml
@model Tease_Server.Models.Page

@{
    ViewBag.Title = "Eliminar";
}

<h2>@Model.Project.Name - Eliminar página</h2>

<h3>¿Estás seguro de que quieres eliminar esta página?</h3>
<fieldset>
    <legend>Página</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
    <div class="display-label">
         @Html.DisplayName("Proyecto")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Project.Name)
    </div>
    <div>
        @Html.DisplayNameFor(model => model.CreationDate)
    </div>
    <div>
        @Html.DisplayFor(model => model.CreationDate)
    </div>
    <div>
        @Html.DisplayNameFor(model => model.ModificationDate)
    </div>
    <div>
        @Html.DisplayFor(model => model.ModificationDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Eliminar" /> |
        Regresar a lista de páginas @Html.ActionLink(Model.Project.Name, "Index", new { projectID = Model.ProjectID})
    </p>
}

Tease Server/Tease Server/Views/Page/Details.cshtml
@model Tease_Server.Models.Page

@{
    ViewBag.Title = "Detalles";
}

<h2>@Model.Project.Name - Detalles de página</h2>

<fieldset>
    <legend>Page</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
    <div class="display-label">
         @Html.DisplayName("Proyecto")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Project.Name)
    </div>
    <div>
        @Html.DisplayNameFor(model => model.CreationDate)
    </div>
    <div>
        @Html.DisplayFor(model => model.CreationDate)
    </div>
    <div>
        @Html.DisplayNameFor(model => model.ModificationDate)
    </div>
    <div>
        @Html.DisplayFor(model => model.ModificationDate)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Editar", "Edit", new { id=Model.PageID }) |
    Regresar a proyecto @Html.ActionLink(Model.Project.Name, "Index", new { projectID = Model.ProjectID })
</p>

Tease Server/Tease Server/Views/Page/Edit.cshtml
@model Tease_Server.Models.Page

@{
    ViewBag.Title = "Edit";
}

<h2>@Model.Project.Name -  Editar</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Página</legend>

        @Html.HiddenFor(model => model.PageID)
        @Html.HiddenFor(model => model.ProjectID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}

<div>
    Regresar a @Html.ActionLink(Model.Project.Name, "Index", new { projectID = Model.ProjectID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tease Server/Tease Server/Views/Page/Index.cshtml
@model IEnumerable<Tease_Server.Models.Page>

@{
    ViewBag.Title = "Páginas";
}

<h2> @ViewBag.ProjectName - Lista de páginas </h2>

<p>
    @Html.ActionLink("Crear nueva", "Create", new { projectID = ViewBag.projectID})
</p>
@if(Model.Count() > 0){
<table>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.PageID }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.PageID }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.PageID }) |
            @Html.ActionLink("Abrir", "Index", "Main", new { pageID = item.PageID }, null) |
            @Html.ActionLink("Descargar", "Zip", new {projectID = item.ProjectID, pageID = item.PageID})
        </td>
    </tr>
}

</table>
    @Html.ActionLink("Regresar a lista de proyectos", "Index", "Project");
}
else{
    <p>Aún no has creado páginas en este proyecto</p>
}