Tease Server/Tease Server/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tease_Server.Models;
using System.IO;
using System.IO.Compression;
using Ionic.Zip;

namespace Tease_Server.Controllers
{
    public class PageController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Page/
        [Authorize]
        public ActionResult Index(int ProjectID=-1)
        {
            try
            {

                if (ProjectID == -1)
                {
                    Redirect("/Project");
                }
                var pages = db.Pages.Where(p => p.ProjectID == ProjectID);
                ViewBag.ProjectID = ProjectID;
                ViewBag.ProjectName = db.Projects.Find(ProjectID).Name;
                return View(pages.ToList());
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Page/Details/5
        [Authorize]
        public ActionResult Details(int id = 0)
        {
            try
            {
                Page page = db.Pages.Find(id);
                if (page == null || page.Project.UserID != getUser().UserId)
                {
                    return HttpNotFound();
                }
                return View(page);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Page/Create
        [Authorize]
        public ActionResult Create(int projectID)
        {
            try
            {
                if (projectID == -1 || db.Projects.Find(projectID).UserID != getUser().UserId)
                {
                    Redirect("/Project");
                }
                ViewBag.ProjectID = projectID.ToString();
                ViewBag.ProjectName = db.Projects.Find(projectID).Name;
                return View();
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // POST: /Page/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Page page)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (db.Pages.Where(x => x.Name == page.Name && x.ProjectID == page.ProjectID).Count() > 0)
                    {
                        ViewBag.DuplicateErrorMessage = "Ya existe un proyecto con ese nombre. Elige otro por favor.";
                        ViewBag.ProjectId = page.ProjectID.ToString();
                        ViewBag.ProjecTName = db.Projects.Find(page.ProjectID).Name;

                        return View(page);
                    }
                    page.ModificationDate = DateTime.Now;
                    page.CreationDate = DateTime.Now;
                    db.Pages.Add(page);
                    db.SaveChanges();
                    createFiles(page.PageID, page.ProjectID);
                    return RedirectToAction("Index", new { projectID = page.ProjectID });
                }

                ViewBag.ProjectID = 0;
                return View(page);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Page/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            try
            {
                Page page = db.Pages.Find(id);
                if (page == null || page.Project.UserID != getUser().UserId)
                {
                    return HttpNotFound();
                }
                ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "Name", page.ProjectID);
                return View(page);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // POST: /Page/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Page page)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Page p = db.Pages.Find(page.PageID);
                    db.Pages.Attach(p);
                    p.Name = page.Name;
                    p.ModificationDate = DateTime.Now;
                    db.SaveChanges();
                    return RedirectToAction("Index", new { projectID = page.ProjectID });
                }
                ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "Name", page.ProjectID);
                return View(page);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Page/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            try
            {
                Page page = db.Pages.Find(id);
                if (page == null || page.Project.UserID != getUser().UserId)
                {
                    return HttpNotFound();
                }
                return View(page);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // POST: /Page/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Page page = db.Pages.Find(id);
                db.Pages.Remove(page);
                db.SaveChanges();
                return RedirectToAction("Index", new { projectID = page.ProjectID });
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // Get /Page/Zip?pageID=1;projectID=1
        public ActionResult Zip(int projectID, int pageID)
        {
            Page page = db.Pages.Find(pageID);
            string directoryPath = Server.MapPath("/PagesFiles/" + projectID.ToString() + "/");
            using (ZipFile file = new ZipFile())
            {
                file.AddDirectory(directoryPath + "res/", page.Project.Name + "/res/");
                directoryPath = directoryPath + pageID.ToString() + "/";
                if (System.IO.File.Exists(directoryPath + "page.zip"))
                {
                    System.IO.File.Delete(directoryPath + "page.zip");
                }
                file.AddDirectory(directoryPath, page.Project.Name + "/" + page.Name + "/");
                file.Save(directoryPath + "page.zip");
            }
            return base.File(directoryPath + "page.zip", "application/zip");
        }

        private UserProfile getUser()
        {
            var user = from s in db.UserProfiles
                       where String.Equals(s.UserName, User.Identity.Name)
                       select s;
            return user.ToList()[0];
        }

        private void createFiles(int pageID, int projectID)
        {
            string path = Server.MapPath("~/PagesFiles/" + projectID.ToString() + "/" + pageID.ToString() + "/");
            if(Directory.Exists(path) == false)
            {
                Directory.CreateDirectory(path);
            }

            if (Directory.Exists(Server.MapPath("/EnvironmentFiles/" + pageID.ToString() + "/")) == false)
            {
                Directory.CreateDirectory(Server.MapPath("/EnvironmentFiles/" + pageID.ToString() + "/"));
            }
            FileStream file;
            file = System.IO.File.Create(path + "page1.html");
            file.Close();
            file = System.IO.File.Create(path + "page1-styles.css");
            file.Close();
            file = System.IO.File.Create(path + "page1-animations.css");
            file.Close();
            file = System.IO.File.Create(path + "page1.js");
            file.Close();
            file = System.IO.File.Create(Server.MapPath("~/EnvironmentFiles/" + pageID.ToString() + "/environment.txt"));
            file.Close();
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Tease Server/Tease Server/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tease_Server.Models;
using Ionic.Zip;

namespace Tease_Server.Controllers
{
    public class ProjectController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Project/

        [Authorize]
        public ActionResult Index()
        {
            try
            {
                UserProfile user = getUser();
                var projects = from p in db.Projects
                               where p.UserID == user.UserId
                               select p;
                return View(projects.ToList());
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Details/5
        [Authorize]
        public ActionResult Details(int id = 0)
        {
            try
            {
                UserProfile user = getUser();
                Project project = db.Projects.Find(id);
                if (project == null || project.UserID != user.UserId)
                {
                    return HttpNotFound();
                }
                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Project/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Project project)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (db.Projects.Where(x => x.Name == project.Name).Count() > 0)
                    {
                        ViewBag.DuplicateErrorMessage = "Ya existe un proyecto con ese nombre. Elige otro por favor.";
                        return View(project);
                    }
                    project.ModificationDate = DateTime.Now;
                    project.CreationDate = DateTime.Now;
                    project.UserID = getUser().UserId;
                    db.Projects.Add(project);
                    db.SaveChanges();
                    System.IO.Directory.CreateDirectory(Server.MapPath("~/PagesFiles/" + project.ProjectID + "/res/"));
                    return RedirectToAction("Index");
                }

                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            try
            {
                Project project = db.Projects.Find(id);
                if (project == null || project.User.UserName != User.Identity.Name)
                {
                    return HttpNotFound();
                }
                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // POST: /Project/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Project project)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Project p = db.Projects.Find(project.ProjectID);
                    if (p.UserID == getUser().UserId)
                    {
                        db.Projects.Attach(p);
                        p.Name = project.Name;
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            try
            {
                Project project = db.Projects.Find(id);
                UserProfile user = getUser();
                if (project == null || user.UserId != project.UserID)
                {
                    return HttpNotFound();
                }
                return View(project);
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // POST: /Project/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Project project = db.Projects.Find(id);
                if (project.UserID == getUser().UserId)
                {
                    db.Projects.Remove(project);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Redirect("/");
                return View();
            }
        }

        //
        // GET: /Project/Zip/projectID

        [Authorize]
        public ActionResult Zip(int projectID)
        {
            string directoryPath = Server.MapPath("/PagesFiles/" + projectID + "/");
            using (ZipFile file = new ZipFile())
            {
                Project project = db.Projects.Find(projectID);
                var pages = from p in db.Pages
                             where p.ProjectID == projectID
                             select p;

                foreach (Page p in pages.ToList())
                {
                    if (System.IO.File.Exists(directoryPath + p.PageID + "/page.zip"))
                    {
                        System.IO.File.Delete(directoryPath + p.PageID + "/page.zip");
                    }
                    file.AddDirectory(directoryPath + p.PageID, project.Name + "/" + p.Name); 
                }
                file.AddDirectory(directoryPath + "res", project.Name + "/res");
                file.Save(directoryPath + "project.zip");
            }
            return base.File(directoryPath + "project.zip", "application/zip");
        }
        
        private UserProfile getUser()
        {
            var user = from s in db.UserProfiles
                       where String.Equals(s.UserName, User.Identity.Name)
                       select s;
            return user.ToList()[0];
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Tease Server/Tease Server/Views/Project/Create.cshtml
@model Tease_Server.Models.Project

@{
    ViewBag.Title = "Crear Proyecto";
}

<h2>Crear Proyecto</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    @ViewBag.DuplicateErrorMessage
    <fieldset>
        <legend>Crear proyecto</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Crear" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tease Server/Tease Server/Views/Project/Delete.cshtml
@model Tease_Server.Models.Project

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>¿Estás seguro de que quieres eliminar el proyecto?</h3>
<fieldset>
    <legend>Proyecto</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreationDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreationDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ModificationDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ModificationDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Eliminar" /> |
        @Html.ActionLink("Regresar", "Index")
    </p>
}

Tease Server/Tease Server/Views/Project/Details.cshtml
@model Tease_Server.Models.Project

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<fieldset>
    <legend>Proyecto</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreationDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreationDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ModificationDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ModificationDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Editar", "Edit", new { id=Model.ProjectID }) |
    @Html.ActionLink("Regresar", "Index")
</p>

Tease Server/Tease Server/Views/Project/Edit.cshtml
@model Tease_Server.Models.Project

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Proyecto</legend>

        @Html.HiddenFor(model => model.ProjectID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tease Server/Tease Server/Views/Project/Index.cshtml
@model IEnumerable<Tease_Server.Models.Project>

@{
    ViewBag.Title = "Lista de proyectos";
}

<h2>Lista de proyectos</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
@if (Model.Count()>0) {
<table>
    <tr>
        <th>
            
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ProjectID }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.ProjectID }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.ProjectID }) |
            @Html.ActionLink("Abrir", "Index", "Page", new {projectId=item.ProjectID}, null) |
            @Html.ActionLink("Descargar", "Zip", new {projectID = item.ProjectID})
        </td>
    </tr>
}
    
</table>
}
else
{
    <p>
        No tienes ningún proyecto.
    </p>
}